---
- hosts: all
  become: yes
  tasks:

  - name: query linux kernel release
    shell: uname -r | xargs
    register: kernel_release 
    
  - name: Add docker Key
    command: bash -c 'echo deb https://apt.dockerproject.org/repo ubuntu-trusty main > /etc/apt/sources.list.d/docker.list' && apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:11371 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D creates=/etc/apt/sources.list.d/docker.list
  
  - name: Remove lxc-docker Package
    apt:
      name: lxc-docker
      state: absent
      purge: yes
      force: yes
    register: result
    until: result | success
    
  - name: Install Docker
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
      force: yes
    with_items:
#      - linux-image-extra-{{ kernel_release.stdout }}
#      - linux-headers-generic
      - docker-engine
      - python-pip
    retries: 5
    delay: 10
    register: result
    until: result | success
    when: ansible_lsb.id == 'LinuxMint'

  - name: Install Docker
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
      force: yes
    with_items:
#      - linux-image-extra-{{ kernel_release.stdout }}
#      - linux-headers-generic
      - docker
      - python-pip
    retries: 5
    delay: 10
    register: result
    until: result | success
    when: ansible_lsb.id == 'Ubuntu'
    
  - debug:
        msg: "ansible_lsb.id is {{ ansible_lsb.id }}"
    
  - name: install docker-py
    pip:
      name: docker-py
    
  - name: docker group
    group:
      name: docker
      state: present
      system: yes
  
  - name: enable docker service
    service:
      name: docker
      enabled: yes
  
  - name: start docker service
    service:
      name: docker
      state: started

  - name: get the username running the deploy
    shell: whoami | xargs
    register: current_username
         
  - name: add "{{ current_username.stdout }}" to docker group
    user:
      name: "{{ current_username.stdout }}"
      groups: docker
      append: yes
   
  - name: update docker image
    docker_image:
      name: smankoo/netmon
      state: present
      force: yes

  - name: remove docker container
    docker_container:
      name: netmon
      image: smankoo/netmon
      state: absent
  
  - name: start docker container
    docker_container:
      name: netmon
      image: smankoo/netmon
      state: started
      interactive: yes
      tty: yes
      detach: yes
      restart_policy: always
      volumes:
        - /netmon-logs:/var/log/netmon-logs
